# Generated by Django 6.0.6 on 2026-08-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('budget_alert', 'Budget Alert'), ('savings_goal', 'Savings Goal'), ('general', 'General'), ('expense', 'Expense'), ('income', 'Income'), ('budget', 'Budget'), ('budget_warning', 'Budget Warning'), ('budget_exceeded', 'Budget Exceeded'), ('achievement', 'Achievement'), ('monthly_report', 'Monthly Report'), ('reminder', 'Reminder'), ('admin', 'Admin')], default='general', max_length=20),
        ),
    ]
