# Generated by Django 6.0.6 on 2026-07-15 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savingsgoal",
            options={"ordering": ["target_date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="savingsgoal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savingsgoal",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="savingsgoal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
