# Generated by Django 6.0.6 on 2026-07-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0003_savingstransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingsgoal",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="savingsgoal",
            name="is_purchased",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="savingsgoal",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savingsgoal",
            name="purchase_note",
            field=models.TextField(blank=True),
        ),
    ]
