# Generated by Django 6.0.6 on 2026-07-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0004_savingsgoal_is_archived_savingsgoal_is_purchased_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Travel", "Travel"),
                    ("Shopping", "Shopping"),
                    ("Education", "Education"),
                    ("Entertainment", "Entertainment"),
                    ("Healthcare", "Healthcare"),
                    ("Bills", "Bills"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                max_length=30,
            ),
        ),
    ]
