# Generated by Django 6.0.6 on 2026-08-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0005_alter_budget_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingsgoal",
            name="goal_category",
            field=models.CharField(blank=True, choices=[("ELECTRONICS", "Electronics"), ("SHOPPING", "Shopping"), ("SPORTS_FITNESS", "Sports & Fitness"), ("TRAVEL", "Travel"), ("EDUCATION", "Education"), ("EMERGENCY", "Emergency"), ("HOME_LIFESTYLE", "Home & Lifestyle"), ("OTHER", "Other")], default="OTHER", max_length=20),
        ),
        migrations.AddField(
            model_name="savingsgoal",
            name="goal_type",
            field=models.CharField(choices=[("PURCHASE", "Purchase"), ("TRAVEL", "Travel & Experience"), ("FUND", "Fund"), ("EDUCATION", "Education"), ("GENERAL", "General Savings"), ("OTHER", "Other")], default="PURCHASE", max_length=20),
        ),
    ]
