# Generated by Django 6.0.6 on 2026-08-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0006_savingsgoal_goal_category_savingsgoal_goal_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsgoal",
            name="goal_category",
            field=models.CharField(blank=True, choices=[("ELECTRONICS", "Electronics"), ("SHOPPING", "Shopping"), ("SPORTS_FITNESS", "Sports & Fitness"), ("HEALTH_MEDICAL", "Health & Medical"), ("EMERGENCY_SAFETY", "Emergency & Safety"), ("CELEBRATIONS_GIFTS", "Celebrations & Gifts"), ("HOME_LIFESTYLE", "Home & Lifestyle"), ("OTHER", "Other")], default="OTHER", max_length=20),
        ),
    ]
