# Generated by Django 6.0.6 on 2026-07-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="source",
            field=models.CharField(
                choices=[
                    ("Salary", "Salary"),
                    ("Pocket Money", "Pocket Money"),
                    ("Scholarship", "Scholarship"),
                    ("Freelance", "Freelance"),
                    ("Business", "Business"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
